### ISSUE TITLE
Doesn't launch

### ISSUE THREAD

**Issue by aaronspe** [ElGatoLoco/cardmintano#1]
Command failed: /Applications/Cardmintano.app/Contents/Resources/scripts/query-address.sh /Applications/Cardmintano.app/Contents/Resources/scripts/query-address.sh: line 3: /Users/a4/Library/Application Support/Cardmintano/data/payment.addr: No such file or directory /Applications/Cardmintano.app/Contents/Resources/scripts/query-address.sh: line 3: /Applications/Daedalus Testnet.app/Contents/MacOS/cardano-cli: No such file or directory

**Comment by ElGatoLoco** [comment]
Do you have Daedalus Testnet installed and running on your system?

**Comment by alex-stout** [comment]
@aaronspe it looks like you don't have the TESTNET version of Daedalus installed.

You can get it here: https://developers.cardano.org/en/testnets/cardano/get-started/wallet/

Edit: You'll also have to get some ada from the faucet for the testnet. You can do that here: https://developers.cardano.org/en/testnets/cardano/tools/faucet/

**Comment by aaronspe** [comment]
Ah, thank you.

**Comment by aaronspe** [comment]
I downloaded and funded the testnet. Cardminto still errors on launch. "user"/Library/Application Support/Cardmintano/data/payment.addr - no such file or directory.  I opened up the directory and only thing in the data folder is the policy stuff.

**Comment by ElGatoLoco** [comment]
@aaronspe I'm not sure how did you manage to fund the address if you don't have one in the first place. 😕 
Also, it's pretty weird that you have policy related stuff and no address, since both things depend on having cardano-cli and $APP_DATA_DIR available, so in theory I'd expect them both to either succeed or fail.

Could you try deleting the whole data directory, starting Daedalus Testnet wallet, waiting for it to fully sync with the network and after that starting Cardmintano again? It should then recreate the directory and you should be given a new address and all the required stuff.

**Comment by alex-stout** [comment]
@ElGatoLoco I've been messing around with this and got it working for the Mainnet. One thing that I ran into was that even with Daedalus fully sync'd, there were situations when the socket wouldn't be opened for a while and would error out on the socket connect.

That being said, it is odd that the policy creation would succeed but not the address creation. From a design perspective do you think breaking the scripts out into their own step and then processing them sequentially would help? That way the error handling might be a little more graceful.

**Comment by ElGatoLoco** [comment]
@alex-stout Hey, glad you made it work on the mainnet. Not sure though what could be the issue with the socket - it should either be there or not when the script executes. Please, open a separate issue if you're able to reproduce it consistently.

Regarding breaking the scripts into their own steps, I agree, and it will definitely be done this way once there's support for different policies, addresses, metadata, etc. For this first version I just went with the shortest path from shell scripts to having a working app.

With that said, feel free to open a PR if you implement something. 🍻

**Comment by aaronspe** [comment]
@ElGatoLoco Hey, just got back to this. I deleted the lib/application support directory and it's working as expected. Thanks for the help to both you and @alex-stout. Tried to name a token A2 & got the please match format pop up, but doesn't tell me what the format is. (i figured it out.) Thanks again.
